ci: run tf apply and destroy on CI

diff --git a/.github/workflows/sanity-checks.yml b/.github/workflows/sanity-checks.yml
--- a/.github/workflows/sanity-checks.yml
+++ b/.github/workflows/sanity-checks.yml
@@ -13,6 +13,7 @@ on:
         required: false
 
 jobs:
+  # Integration Tests against Test Deployment
   test_url_uload:
     runs-on: ubuntu-latest
     env:
@@ -25,51 +26,54 @@ jobs:
         with:
           terraform_version: "1.9.8"
 
-      # - run: terraform init
-      # - id: plan
-      #   run: terraform plan -no-color
+      - name: Terraform Init
+        working-directory: terraform
+        run: terraform init
+
+      # TF PLAN
+      - name: Terraform Plan
+        working-directory: terraform
+        run: terraform plan -var-file=${{ inputs.env_var_file }} -out tfplan
 
       # - run: echo ${{ steps.plan.outputs.stdout }}
       # - run: echo ${{ steps.plan.outputs.stderr }}
       # - run: echo ${{ steps.plan.outputs.exitcode }}
 
-      - name: Terraform Init
-        working-directory: terraform
-        run: terraform init
-
-      # Step 4: Terraform Apply (Setup Test Environment)
+      # TF APPLY
       - name: Terraform Apply
         working-directory: terraform
         id: apply
+        # tf apply and "capture" human-readable plan output
         run: |
-          terraform apply -auto-approve --var-file=${{ inputs.env_var_file }}
+          set -o pipefail  # prevent errors in a pipeline from being masked.
+          terraform apply -auto-approve tfplan | tee apply_output.txt
 
-      # Step 5: Call API Gateway to Receive Pre-signed URL
-      - name: Get Pre-signed URL from API Gateway
-        id: get_presigned_url
-        run: |
-          GATEWAY_URL=$(terraform output -raw api_invoke_url)
-          RESPONSE=$(curl -X GET "$GATEWAY_URL/get-presigned-url?object_name=dummy_test_file.txt")
-          echo "Response from API Gateway: $RESPONSE"
-          echo "RESPONSE=$RESPONSE" >> $GITHUB_ENV
+      # # START TEST SCENARIO
+      # - name: Get Pre-signed URL from API Gateway
+      #   id: get_presigned_url
+      #   run: |
+      #     GATEWAY_URL=$(terraform output -raw api_invoke_url)
+      #     RESPONSE=$(curl -X GET "$GATEWAY_URL/get-presigned-url?object_name=dummy_test_file.txt")
+      #     echo "Response from API Gateway: $RESPONSE"
+      #     echo "RESPONSE=$RESPONSE" >> $GITHUB_ENV
 
-      # Step 6: Upload File Using Pre-signed URL
-      - name: Upload Dummy File to S3
-        if: ${{ success() }}
-        run: |
-          PRESIGNED_URL=$(echo "$RESPONSE" | jq -r '.presigned_url')
-          echo "Using Pre-signed URL: $PRESIGNED_URL"
-          echo "Sample data" > dummy_test_file.txt
-          curl -X PUT -T "dummy_test_file.txt" "$PRESIGNED_URL"
+      # # Upload File Using Pre-signed URL
+      # - name: Upload Dummy File to S3
+      #   if: ${{ success() }}
+      #   run: |
+      #     PRESIGNED_URL=$(echo "$RESPONSE" | jq -r '.presigned_url')
+      #     echo "Using Pre-signed URL: $PRESIGNED_URL"
+      #     echo "Sample data" > dummy_test_file.txt
+      #     curl -X PUT -T "dummy_test_file.txt" "$PRESIGNED_URL"
 
-      # Step 7: Verify File Upload in S3
-      - name: Verify File Upload in S3
-        if: ${{ success() }}
-        run: |
-          BUCKET_NAME=$(terraform output -raw bucket_name)
-          aws s3 ls s3://$BUCKET_NAME/dummy_test_file.txt || exit 1
+      # # ASSERT: Verify File Upload in S3
+      # - name: Verify File Upload in S3
+      #   if: ${{ success() }}
+      #   run: |
+      #     BUCKET_NAME=$(terraform output -raw bucket_name)
+      #     aws s3 ls s3://$BUCKET_NAME/dummy_test_file.txt || exit 1
 
-      # Final Step: Terraform Destroy (Cleanup)
+      # TEARDOWN: Terraform Destroy (Cleanup)
       - name: Terraform Destroy
         if: always()
         working-directory: terraform
